import type { WorkflowDef } from '../types';

// Workflow A — Anomaly & RCA rApp
// Layout: left column = rApp chain, right column = VISMON AI, bottom = NOC/Validation
export const anomalyRcaWorkflow: WorkflowDef = {
  id: 'anomaly-rca',
  name: 'Anomaly & RCA rApp',
  shortName: 'Anomaly RCA',
  nodes: [
    {
      id: 'kpi-ingestion',
      label: 'KPI Ingestion',
      sublabel: 'O1/E2-like Interface',
      x: 80,
      y: 60,
      width: 180,
      height: 60,
      type: 'kpi',
    },
    {
      id: 'rapp-sensor',
      label: 'Network Anomaly',
      sublabel: 'Detector rApp',
      x: 80,
      y: 180,
      width: 180,
      height: 60,
      type: 'rapp',
    },
    {
      id: 'decision-anomaly',
      label: 'Performance Usage',
      sublabel: 'Drop Detected?',
      x: 80,
      y: 300,
      width: 180,
      height: 60,
      type: 'decision',
    },
    {
      id: 'enrichment',
      label: 'Collect UE &',
      sublabel: 'Cell Metrics',
      x: 80,
      y: 420,
      width: 180,
      height: 60,
      type: 'rapp',
    },
    {
      id: 'vismon-ai',
      label: 'VISMON AI',
      sublabel: 'RCA + Recommendations',
      x: 380,
      y: 300,
      width: 180,
      height: 60,
      type: 'ai',
    },
    {
      id: 'rapp-decision',
      label: 'rApp Evaluates',
      sublabel: 'Recommendation',
      x: 380,
      y: 420,
      width: 180,
      height: 60,
      type: 'rapp',
    },
    {
      id: 'noc-alert',
      label: 'User Alerted',
      sublabel: 'NOC / BAU Alarm',
      x: 80,
      y: 560,
      width: 180,
      height: 60,
      type: 'noc',
    },
    {
      id: 'netops-rapp',
      label: 'Network Operations',
      sublabel: 'rApp (Execution)',
      x: 380,
      y: 560,
      width: 180,
      height: 60,
      type: 'netops',
    },
    {
      id: 'validation',
      label: 'Validate &',
      sublabel: 'Post-check',
      x: 230,
      y: 680,
      width: 180,
      height: 60,
      type: 'validation',
    },
  ],
  edges: [
    { id: 'e1', from: 'kpi-ingestion', to: 'rapp-sensor', label: 'RAN KPIs' },
    { id: 'e2', from: 'rapp-sensor', to: 'decision-anomaly', label: 'Sense' },
    { id: 'e3', from: 'decision-anomaly', to: 'enrichment', label: 'Yes' },
    { id: 'e4', from: 'enrichment', to: 'vismon-ai', label: 'Northbound API' },
    { id: 'e5', from: 'vismon-ai', to: 'rapp-decision', label: 'RCA Result' },
    { id: 'e6', from: 'rapp-decision', to: 'noc-alert', label: 'Alert' },
    { id: 'e7', from: 'rapp-decision', to: 'netops-rapp', label: 'Trigger' },
    { id: 'e8', from: 'noc-alert', to: 'validation', label: 'Confirm' },
    { id: 'e9', from: 'netops-rapp', to: 'validation', label: 'Execute' },
    {
      id: 'e10',
      from: 'decision-anomaly',
      to: 'rapp-sensor',
      label: 'No',
      style: 'dashed',
      waypoints: [{ x: 40, y: 330 }, { x: 40, y: 210 }],
    },
  ],
  eventSequence: [
    { from: 'kpi-ingestion', to: 'rapp-sensor', payload_type: 'RAN_KPI_BATCH', baseLatency: 120, failRate: 0.02 },
    { from: 'rapp-sensor', to: 'decision-anomaly', payload_type: 'ANOMALY_SCORE', baseLatency: 80, failRate: 0.05 },
    { from: 'decision-anomaly', to: 'enrichment', payload_type: 'ANOMALY_DETECTED', baseLatency: 40, failRate: 0.0 },
    { from: 'enrichment', to: 'vismon-ai', payload_type: 'ENRICHED_CONTEXT', baseLatency: 200, failRate: 0.03 },
    { from: 'vismon-ai', to: 'rapp-decision', payload_type: 'RCA_RECOMMENDATION', baseLatency: 350, failRate: 0.04 },
    { from: 'rapp-decision', to: 'noc-alert', payload_type: 'ALARM_EVENT', baseLatency: 60, failRate: 0.01 },
    { from: 'rapp-decision', to: 'netops-rapp', payload_type: 'EXECUTE_COMMAND', baseLatency: 90, failRate: 0.05 },
    { from: 'netops-rapp', to: 'validation', payload_type: 'ACTION_RESULT', baseLatency: 150, failRate: 0.03 },
  ],
};
