import type { WorkflowDef } from '../types';

// Workflow D — Intelligent Energy rApp
export const intelligentEnergyWorkflow: WorkflowDef = {
  id: 'intelligent-energy',
  name: 'Intelligent Energy rApp',
  shortName: 'Energy Saving',
  nodes: [
    {
      id: 'utilization-sensor',
      label: 'Utilization Monitor',
      sublabel: 'Traffic / PRB / UEs (O1/E2)',
      x: 80,
      y: 60,
      width: 180,
      height: 60,
      type: 'kpi',
    },
    {
      id: 'rapp-energy',
      label: 'Intelligent Energy',
      sublabel: 'rApp (Sensor)',
      x: 80,
      y: 180,
      width: 180,
      height: 60,
      type: 'rapp',
    },
    {
      id: 'decision-energy',
      label: 'Energy Saving',
      sublabel: 'Criteria Fulfilled?',
      x: 80,
      y: 300,
      width: 180,
      height: 60,
      type: 'decision',
    },
    {
      id: 'candidate-eval',
      label: 'Identify Candidate',
      sublabel: 'Cells / RUs',
      x: 80,
      y: 420,
      width: 180,
      height: 60,
      type: 'rapp',
    },
    {
      id: 'netops-rapp',
      label: 'Network Operations',
      sublabel: 'rApp (Execution)',
      x: 380,
      y: 300,
      width: 180,
      height: 60,
      type: 'netops',
    },
    {
      id: 'handover-users',
      label: 'Handover Users',
      sublabel: 'to Adjacent Cells',
      x: 380,
      y: 420,
      width: 180,
      height: 60,
      type: 'netops',
    },
    {
      id: 'lock-ru',
      label: 'Lock & Power Down',
      sublabel: 'RU / Cell',
      x: 380,
      y: 540,
      width: 180,
      height: 60,
      type: 'netops',
    },
    {
      id: 'vismon-energy',
      label: 'VISMON Energy',
      sublabel: 'Power Measurement',
      x: 600,
      y: 420,
      width: 180,
      height: 60,
      type: 'ai',
    },
    {
      id: 'reactivation',
      label: 'Re-activate RU',
      sublabel: 'When Traffic Returns',
      x: 380,
      y: 660,
      width: 180,
      height: 60,
      type: 'netops',
    },
    {
      id: 'validation',
      label: 'Validate Energy',
      sublabel: 'vs QoE',
      x: 600,
      y: 540,
      width: 180,
      height: 60,
      type: 'validation',
    },
  ],
  edges: [
    { id: 'e1', from: 'utilization-sensor', to: 'rapp-energy', label: 'RAN KPIs' },
    { id: 'e2', from: 'rapp-energy', to: 'decision-energy', label: 'Sense' },
    { id: 'e3', from: 'decision-energy', to: 'candidate-eval', label: 'Yes' },
    { id: 'e4', from: 'candidate-eval', to: 'netops-rapp', label: 'Candidate List' },
    { id: 'e5', from: 'netops-rapp', to: 'handover-users', label: 'Step 1' },
    { id: 'e6', from: 'handover-users', to: 'lock-ru', label: 'Step 2' },
    { id: 'e7', from: 'lock-ru', to: 'vismon-energy', label: 'Power Data' },
    { id: 'e8', from: 'vismon-energy', to: 'validation', label: 'Measure' },
    { id: 'e9', from: 'lock-ru', to: 'reactivation', label: 'Monitor' },
    { id: 'e10', from: 'reactivation', to: 'rapp-energy', label: 'Feedback Loop', style: 'dashed' },
    {
      id: 'e11',
      from: 'decision-energy',
      to: 'rapp-energy',
      label: 'No',
      style: 'dashed',
      waypoints: [{ x: 40, y: 330 }, { x: 40, y: 210 }],
    },
  ],
  eventSequence: [
    { from: 'utilization-sensor', to: 'rapp-energy', payload_type: 'UTILIZATION_METRICS', baseLatency: 130, failRate: 0.02 },
    { from: 'rapp-energy', to: 'decision-energy', payload_type: 'ENERGY_SCORE', baseLatency: 90, failRate: 0.03 },
    { from: 'decision-energy', to: 'candidate-eval', payload_type: 'SAVING_TRIGGER', baseLatency: 50, failRate: 0.0 },
    { from: 'candidate-eval', to: 'netops-rapp', payload_type: 'CANDIDATE_CELLS', baseLatency: 110, failRate: 0.02 },
    { from: 'netops-rapp', to: 'handover-users', payload_type: 'HANDOVER_CMD', baseLatency: 220, failRate: 0.05 },
    { from: 'handover-users', to: 'lock-ru', payload_type: 'LOCK_CMD', baseLatency: 180, failRate: 0.03 },
    { from: 'lock-ru', to: 'vismon-energy', payload_type: 'POWER_TELEMETRY', baseLatency: 250, failRate: 0.02 },
    { from: 'vismon-energy', to: 'validation', payload_type: 'ENERGY_REPORT', baseLatency: 200, failRate: 0.02 },
  ],
};
