import type { WorkflowDef } from '../types';

// Workflow B — Network Assurance rApp
// Track critical UEs (SUPI), detect degradation, RCA via VISMON AI, execute via NetOps
export const networkAssuranceWorkflow: WorkflowDef = {
  id: 'network-assurance',
  name: 'Network Assurance rApp',
  shortName: 'Net Assurance',
  nodes: [
    {
      id: 'ue-tracker',
      label: 'UE Tracker',
      sublabel: 'SUPI / Critical UEs',
      x: 80,
      y: 60,
      width: 180,
      height: 60,
      type: 'kpi',
    },
    {
      id: 'rapp-assurance',
      label: 'Network Assurance',
      sublabel: 'rApp (Sensor)',
      x: 80,
      y: 180,
      width: 180,
      height: 60,
      type: 'rapp',
    },
    {
      id: 'decision-tput',
      label: 'TPut / QoS',
      sublabel: 'Drop Detected?',
      x: 80,
      y: 300,
      width: 180,
      height: 60,
      type: 'decision',
    },
    {
      id: 'metric-collect',
      label: 'Collect Network',
      sublabel: '& UE Metrics',
      x: 80,
      y: 420,
      width: 180,
      height: 60,
      type: 'rapp',
    },
    {
      id: 'vismon-ai',
      label: 'VISMON AI',
      sublabel: 'RCA + Recommendation',
      x: 380,
      y: 300,
      width: 180,
      height: 60,
      type: 'ai',
    },
    {
      id: 'policy-eval',
      label: 'Policy Evaluation',
      sublabel: 'SLA / Slice / QoS Rules',
      x: 380,
      y: 420,
      width: 180,
      height: 60,
      type: 'rapp',
    },
    {
      id: 'netops-rapp',
      label: 'Network Operations',
      sublabel: 'rApp (Execution)',
      x: 380,
      y: 560,
      width: 180,
      height: 60,
      type: 'netops',
    },
    {
      id: 'noc-alarm',
      label: 'NOC / BAU',
      sublabel: 'Tailored Alarm',
      x: 80,
      y: 560,
      width: 180,
      height: 60,
      type: 'noc',
    },
    {
      id: 'user-alert',
      label: 'User Alerted',
      sublabel: 'Recommendation Proposed',
      x: 80,
      y: 680,
      width: 180,
      height: 60,
      type: 'noc',
    },
    {
      id: 'validation',
      label: 'Validate',
      sublabel: 'Service Restored',
      x: 380,
      y: 680,
      width: 180,
      height: 60,
      type: 'validation',
    },
  ],
  edges: [
    { id: 'e1', from: 'ue-tracker', to: 'rapp-assurance', label: 'KPIs / SUPI' },
    { id: 'e2', from: 'rapp-assurance', to: 'decision-tput', label: 'Sense' },
    { id: 'e3', from: 'decision-tput', to: 'metric-collect', label: 'Yes' },
    { id: 'e4', from: 'metric-collect', to: 'vismon-ai', label: 'Northbound API' },
    { id: 'e5', from: 'vismon-ai', to: 'policy-eval', label: 'RCA Result' },
    { id: 'e6', from: 'policy-eval', to: 'netops-rapp', label: 'Best Action' },
    { id: 'e7', from: 'policy-eval', to: 'noc-alarm', label: 'Raise Alarm' },
    { id: 'e8', from: 'noc-alarm', to: 'user-alert', label: 'Notify' },
    { id: 'e9', from: 'netops-rapp', to: 'validation', label: 'Execute' },
    {
      id: 'e10',
      from: 'decision-tput',
      to: 'rapp-assurance',
      label: 'No',
      style: 'dashed',
      waypoints: [{ x: 40, y: 330 }, { x: 40, y: 210 }],
    },
  ],
  eventSequence: [
    { from: 'ue-tracker', to: 'rapp-assurance', payload_type: 'UE_KPI_STREAM', baseLatency: 100, failRate: 0.02 },
    { from: 'rapp-assurance', to: 'decision-tput', payload_type: 'QOS_SCORE', baseLatency: 90, failRate: 0.04 },
    { from: 'decision-tput', to: 'metric-collect', payload_type: 'DEGRADATION_EVENT', baseLatency: 50, failRate: 0.0 },
    { from: 'metric-collect', to: 'vismon-ai', payload_type: 'ENRICHED_UE_CONTEXT', baseLatency: 180, failRate: 0.03 },
    { from: 'vismon-ai', to: 'policy-eval', payload_type: 'RCA_RESULT', baseLatency: 320, failRate: 0.04 },
    { from: 'policy-eval', to: 'netops-rapp', payload_type: 'ACTION_COMMAND', baseLatency: 70, failRate: 0.05 },
    { from: 'policy-eval', to: 'noc-alarm', payload_type: 'ALARM_PAYLOAD', baseLatency: 60, failRate: 0.01 },
    { from: 'netops-rapp', to: 'validation', payload_type: 'EXECUTION_RESULT', baseLatency: 200, failRate: 0.04 },
  ],
};
