import type { WorkflowDef } from '../types';

// Workflow C — PCI Clash rApp
export const pciClashWorkflow: WorkflowDef = {
  id: 'pci-clash',
  name: 'PCI Clash rApp',
  shortName: 'PCI Clash',
  nodes: [
    {
      id: 'config-sensor',
      label: 'Cell Config &',
      sublabel: 'Neighbor Relations (O1/E2)',
      x: 80,
      y: 60,
      width: 180,
      height: 60,
      type: 'kpi',
    },
    {
      id: 'rapp-pci',
      label: 'PCI Clash',
      sublabel: 'Detection rApp',
      x: 80,
      y: 180,
      width: 180,
      height: 60,
      type: 'rapp',
    },
    {
      id: 'decision-pci',
      label: 'PCI Clash',
      sublabel: 'Detected?',
      x: 80,
      y: 300,
      width: 180,
      height: 60,
      type: 'decision',
    },
    {
      id: 'user-alert',
      label: 'User Alerted',
      sublabel: 'Recommendation Proposed',
      x: 80,
      y: 420,
      width: 180,
      height: 60,
      type: 'noc',
    },
    {
      id: 'vismon-ai',
      label: 'VISMON AI',
      sublabel: 'Compute Best PCI',
      x: 380,
      y: 180,
      width: 180,
      height: 60,
      type: 'ai',
    },
    {
      id: 'pci-calc',
      label: 'Calculate Optimal',
      sublabel: 'PCI Assignment',
      x: 380,
      y: 300,
      width: 180,
      height: 60,
      type: 'ai',
    },
    {
      id: 'netops-rapp',
      label: 'Network Operations',
      sublabel: 'rApp (Execution)',
      x: 380,
      y: 420,
      width: 180,
      height: 60,
      type: 'netops',
    },
    {
      id: 'soft-handover',
      label: 'Soft Handover',
      sublabel: 'Active UEs',
      x: 380,
      y: 540,
      width: 180,
      height: 60,
      type: 'netops',
    },
    {
      id: 'pci-change',
      label: 'Apply New PCI',
      sublabel: 'via Config API',
      x: 560,
      y: 540,
      width: 180,
      height: 60,
      type: 'netops',
    },
    {
      id: 'ru-restart',
      label: 'Restart RU/Cell',
      sublabel: 'Systems Action API',
      x: 560,
      y: 420,
      width: 180,
      height: 60,
      type: 'netops',
    },
    {
      id: 'validation',
      label: 'Validate PCI',
      sublabel: 'Post-check',
      x: 230,
      y: 660,
      width: 180,
      height: 60,
      type: 'validation',
    },
  ],
  edges: [
    { id: 'e1', from: 'config-sensor', to: 'rapp-pci', label: 'Topology View' },
    { id: 'e2', from: 'rapp-pci', to: 'decision-pci', label: 'Sense' },
    { id: 'e3', from: 'decision-pci', to: 'user-alert', label: 'Yes' },
    { id: 'e4', from: 'decision-pci', to: 'vismon-ai', label: 'Call VISMON' },
    { id: 'e5', from: 'vismon-ai', to: 'pci-calc', label: 'Global Knowledge' },
    { id: 'e6', from: 'pci-calc', to: 'netops-rapp', label: 'Best PCI' },
    { id: 'e7', from: 'netops-rapp', to: 'soft-handover', label: 'Step 1' },
    { id: 'e8', from: 'soft-handover', to: 'pci-change', label: 'Step 2' },
    { id: 'e9', from: 'pci-change', to: 'ru-restart', label: 'Step 3' },
    { id: 'e10', from: 'ru-restart', to: 'validation', label: 'Confirm' },
    { id: 'e11', from: 'user-alert', to: 'validation', label: 'Validate' },
    {
      id: 'e12',
      from: 'decision-pci',
      to: 'rapp-pci',
      label: 'No',
      style: 'dashed',
      waypoints: [{ x: 40, y: 330 }, { x: 40, y: 210 }],
    },
  ],
  eventSequence: [
    { from: 'config-sensor', to: 'rapp-pci', payload_type: 'NEIGHBOR_TOPOLOGY', baseLatency: 110, failRate: 0.02 },
    { from: 'rapp-pci', to: 'decision-pci', payload_type: 'PCI_SCAN', baseLatency: 80, failRate: 0.04 },
    { from: 'decision-pci', to: 'vismon-ai', payload_type: 'CLASH_EVENT', baseLatency: 50, failRate: 0.0 },
    { from: 'vismon-ai', to: 'pci-calc', payload_type: 'NETWORK_KNOWLEDGE', baseLatency: 300, failRate: 0.03 },
    { from: 'pci-calc', to: 'netops-rapp', payload_type: 'OPTIMAL_PCI', baseLatency: 120, failRate: 0.02 },
    { from: 'netops-rapp', to: 'soft-handover', payload_type: 'HANDOVER_CMD', baseLatency: 200, failRate: 0.05 },
    { from: 'soft-handover', to: 'pci-change', payload_type: 'PCI_CONFIG', baseLatency: 150, failRate: 0.03 },
    { from: 'pci-change', to: 'ru-restart', payload_type: 'RESTART_CMD', baseLatency: 400, failRate: 0.04 },
    { from: 'ru-restart', to: 'validation', payload_type: 'RESTART_RESULT', baseLatency: 180, failRate: 0.03 },
  ],
};
